### ISSUE TITLE
(for first-time contributor) Nice command line management with argparse

### ISSUE THREAD

**Issue by chaica** [chaica/db2twitter#5]
The goal of this bug report is to write a nice commande-line management using argparse for db2twitter. This bug report should be studied  by a first-time contributor to a free or opensource software. It should lead to a Github Pull Request in order to solve this bug report.

1/ In your Github , fork the repository db2twitter
2/ in the db2twitter module (the db2twitter directory in the root directory) , create a CliParse class . It should have a __init__ , a main() and an attribute cliargs (have a look at the structure of db2twitter/twbuild.py and organize you code the same way, it's pretty simple)
3/ write the unit test to check if your CliParse class works
4/ in main.py ,  you should instantiate CliParse before other objects, get the attribute cliargs
5/ modify the ConfParse class in order ConfParse knows what configuration file it must parse
6/ In your Github generate a Pull Request

I'll be available if you have any question.

Regards,
Carl

**Comment by hughesmc** [comment]
I'm new to open source, and wanted to make chose a fairly straight-forward contribution to see the process.  Is this one still available?

**Comment by chaica** [comment]
Hi,

Thanks for your interest for db2twitter, definitly yes, this one is still available. The description above is not up-to-date though but the contribution is stille quite simple. Here it is ::

- the class CliParse in the file db2twitter/cliparse.py should use the [standard library module argparse](https://docs.python.org/3/library/argparse.html)
- have a look at how the Python argparse module works and replace the existing code of the class CliParse in the file db2twitter/cliparse.py to use the python argparse module. You can also have a look at [the retweet project](https://github.com/chaica/retweet) (one of my other projects) and the file retweet/cliparse.py to read a real world example. 

Regards,
Carl
